title: Tech Study Log
email: jeonalsrn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Semiconductor HW Library Study Archive
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeonmmingu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jeonmmingu

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  topics:
    output: true
    permalink: /topics/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "topics"
    values:
      layout: post